import { GreenhouseArtPanel } from '../GreenhouseArtPanel';
import { CropFieldGuide } from '../CropFieldGuide';
import { ScienceDrawer } from '../ScienceDrawer';
import { cropArt } from '../../content/crop-art';
import { LandingPage } from '../LandingPage';
import { ResourcePanel } from '../ResourcePanel';
import { ModuleCard } from '../ModuleCard';
import { LivestockPanel, UtilityPanel, RepairPanel } from '../ManagementPanels';
import { ForecastPanel, HazardAlert, CrisisOverlay, RecoverySuccess, MissionFailure, TutorialHint } from '../HazardPanels';
import { MissionControlPanel } from '../MissionControlPanel';
import { MissionReport } from '../MissionReport';
import { Leaderboard } from '../Leaderboard';
import { AnalyticsPanel } from '../AnalyticsPanel';
import { PixelAsset } from '../primitives';
import { MODULES } from '../../data/modules';
import { curatedSources } from '../../content/sources';
import s from '../ui.module.css';
const noop = () => {};
const state = { budget: 42, ap: 6, turn: 4, level: 1 as const, resources: { power: 72, water: 38, oxygen: 86, food: 60, temperature: 21 }, production: { cropCumulative: 28, meatCumulative: 12 } };
export function Preview() {
  return <><div className="previewBar"><strong>UI DESIGN PREVIEW · SAMPLE DATA</strong><nav aria-label="Preview screens">{['landing','systems','crops','report','leaderboard','analytics','assets'].map(name => <button data-screen={name} key={name}>{name}</button>)}<a href="original-landing.html">Original design ↗</a></nav></div>
    <section id="landing" className="screen"><LandingPage onStart={noop} /></section>
    <section id="crops" className="screen" hidden><CropFieldGuide /></section>
    <section id="systems" className={`screen ${s.root}`} hidden><header className={s.nav}><div><p className={s.eyebrow}>Progressive / Establishment · sample turn 4</p><h1 style={{fontSize:32}}>Outpost operations</h1></div><p className={s.badge}>Layout locked</p></header><p className="previewOnly">Presentation only. Controls do not resolve turns or alter a game.</p><ResourcePanel state={state} status={{ power:'normal', water:'warning', oxygen:'normal', food:'normal', temperature:'normal' }} productionTargets={{crop:60,meat:25}} />
    <div className={s.twoCol}><div><TutorialHint mode="progressive" level={1} hint="connection" /><div style={{marginTop:20}}><ForecastPanel forecast={{solar:'Elevated',thermal:'Moderate',impact:'Low'}} /></div><h2 style={{marginTop:30}}>Build catalogue</h2><div className={s.twoCol}>{MODULES.filter(m => m.category === 'greenhouse').map(m => <ModuleCard key={m.id} module={m} variant={m.id.endsWith('compact') ? 'Compact' : m.id.endsWith('industrial') ? 'Industrial' : 'Standard'} />)}</div></div><div><div className="stateControls" role="group" aria-label="Preview communication states"><button data-comms="online">Online</button><button data-comms="offline">Link lost</button><button data-comms="unavailable">Service unavailable</button></div>{(['online','offline','unavailable'] as const).map(connection => <div data-comms-panel={connection} hidden={connection !== 'online'} key={connection}><MissionControlPanel connection={connection} loading={connection === 'online'} messages={[{id:'1',sender:'control',text:'The current instability may be linked to utility delivery. I would inspect the greenhouse’s connection path before increasing lighting demand.',timeLabel:'Turn 4'}]} /></div>)}<div className="stateControls" role="group" aria-label="Preview hazard states">{['hazard','crisis','recovery','failure'].map(name => <button data-hazard={name} key={name}>{name}</button>)}</div><div data-hazard-panel="hazard"><HazardAlert type="temperature" /></div><div data-hazard-panel="crisis" hidden><CrisisOverlay trigger="Water supply is critical." recoveryTurn={5} onInspect={noop} /></div><div data-hazard-panel="recovery" hidden><RecoverySuccess /></div><div data-hazard-panel="failure" hidden><MissionFailure reason="Critical water supply was not restored in the recovery turn." onReport={noop} /></div></div></div>
    <div className={s.twoCol}><GreenhouseArtPanel crop="lettuce" stage="growing" settings={{water:'medium',light:'medium',temperature:'medium'}} canCollect={false} onCropIntent={noop} onSettingIntent={noop} onCollectIntent={noop}/><LivestockPanel livestock={{moduleId:'Livestock 01',animal:'chicken',growth:0.5,feed:'normal'}} water={{text:'Delivery low',severity:'warning'}} temperature={{text:'Nominal',severity:'normal'}} onAction={noop}/><UtilityPanel moduleId="Utility 01" allocation={{thermal:0.5,backupPower:0.3,commsBackup:0.2}} options={[{id:'thermal',label:'Thermal support',apCost:1,allocation:{thermal:0.6,backupPower:0.2,commsBackup:0.2}}]} onAction={noop}/><RepairPanel targets={[{id:'corridor-1',label:'Utility corridor 01',integrity:0.65,apCost:2}]} onAction={noop}/></div><ScienceDrawer /><p id="preview-action" role="status" className={s.notice}>Select a control to inspect its presentation. All values above are illustrative.</p></section>
    <section id="report" className="screen" hidden><MissionReport nickname="MoonGardener · illustrative run" scores={{total:82,rules:58,llm:24}} sources={curatedSources} report={{result:'PASS',overview:'This example outpost completed ten turns and met both cumulative production targets.',production:'Crop and meat targets were achieved in this illustrative mission.',stability:'A brief water-delivery crisis was followed by recovery. Review the turn history to understand the sequence.',layout:'The example uses a compact growing area close to supporting utilities.',disasterResponse:'Repairs supported recovery during the mission. A single run cannot establish which intervention was decisive.',agriculture:'Lettuce supplied early harvests. Livestock represents a simplified, speculative lunar food-production trade-off.',missionControl:'The advisor suggested reviewing delivery paths. During the outage, the player relied on local readings.',scientificContext:'Controlled-environment growing research motivates the game’s emphasis on water, light, and temperature. Real experimental results do not validate these game settings.',strategySuggests:'Your strategy suggests a preference for short delivery paths and recovery capacity within this simulation. Comparisons among player runs can suggest hypotheses for further exploration.',sourceIds:['nasa-biomass','nasa-illumination','esa-melissa'],usedFallback:false}} /></section>
    <section id="leaderboard" className="screen" hidden>{(['overall','production','stability','efficiency','resilience'] as const).map((category,i) => <div data-board={category} hidden={i !== 0} key={category}><Leaderboard category={category} onCategoryChange={noop} currentRunId="sample" rows={[{id:'sample',rank:1,nickname:'MoonGardener · sample',mode:'progressive',passed:true,score:[82,24,21,6,5][i]}]}/></div>)}<p className="previewOnly">Illustrative row only. No leaderboard record was submitted.</p></section>
    <section id="analytics" className="screen" hidden><AnalyticsPanel data={{sampleSize:24,layout:{averageCorridorLength:18,averageGreenhouseWaterDistance:3.2,compactGreenhouseShare:0.62,averageResilienceBudgetShare:0},agriculture:{cropMix:{lettuce:22,radish:12,'chili-pepper':8,potato:14,soybean:9,arabidopsis:4},livestockMix:{chicken:19,pig:8,cow:4},averageCropYield:71,averageMeatYield:29}}}/><p className="previewOnly">Illustrative dataset, not observed production data.</p></section>
    <section id="assets" className={`screen ${s.root}`} hidden><p className={s.eyebrow}>Original pixel artwork / cozy-v1</p><h1>Outpost field kit</h1><div className="assetGrid">{['habitat','greenhouse','livestock','oxygen','water','solar','battery','utility','communications','shelter','storage','recreation','corridor'].map(name => <figure key={name}><PixelAsset name={name} size={96}/><figcaption>{name}</figcaption></figure>)}{(['crops','animals','ui'] as const).flatMap(folder => (folder === 'crops' ? cropArt.map(crop => `${crop.id}-ready`) : folder === 'animals' ? ['chicken','pig','cow'] : ['temperature','radiation','micrometeoroid','communications','power']).map(name => <figure key={`${folder}-${name}`}><PixelAsset name={name} folder={folder} size={64}/><figcaption>{name}</figcaption></figure>))}</div><h2 style={{marginTop:32}}>One family. Three scales.</h2><div className="assetGrid">{(['greenhouse','livestock'] as const).flatMap(name => ['compact','standard','industrial'].map(variant => <figure key={`${name}-${variant}`}><PixelAsset name={`${name}-${variant}`} size={192}/><figcaption>{name} · {variant}</figcaption></figure>))}</div><h2 style={{marginTop:32}}>Readable condition states</h2><div className="assetGrid">{['normal','selected','damaged'].map(condition => <figure key={condition}><span className={s.condition} data-condition={condition}><PixelAsset name="habitat" size={192}/>{condition === 'damaged' && <span className={s.damageCrack}><PixelAsset name="damage" folder="ui" size={48}/></span>}</span><figcaption>{condition === 'damaged' ? '⚠ Damaged · inspect repairs' : condition}</figcaption></figure>)}</div><ScienceDrawer /></section></>;
}
