'use client';
import type { CropPlotState, LivestockState, PlayerAction, UtilityAllocation, CropKind, AnimalKind, Setting } from '../game/state/types';
import { Panel, Status, type Severity } from './primitives';
import s from './ui.module.css';
type Controls = { onAction: (action: PlayerAction) => void; disabledReason?: string };
function Select<T extends string>({ label, value, options, onChange, disabled }: { label: string; value: T; options: readonly T[]; onChange: (value: T) => void; disabled?: boolean }) {
  return <label className={s.field}>{label}<select value={value} disabled={disabled} onChange={e => onChange(e.target.value as T)}>{options.map(option => <option key={option} value={option}>{option}</option>)}</select></label>;
}
export function GreenhousePanel({ plot, onAction, disabledReason }: Controls & { plot: CropPlotState }) {
  return <Panel title="Greenhouse" eyebrow={plot.moduleId}><fieldset disabled={!!disabledReason} className={s.fieldset}><Select<CropKind> label="Crop" value={plot.crop ?? 'lettuce'} options={['lettuce','potato','wheat']} onChange={crop => onAction({ type: 'PLANT_CROP', moduleId: plot.moduleId, slotIndex: plot.slotIndex, crop })} />{(['water','light','temperature'] as const).map(key => <Select<Setting> key={key} label={key} value={plot[key]} options={['low','medium','high']} onChange={value => onAction({ type: 'SET_CROP_PARAMS', moduleId: plot.moduleId, slotIndex: plot.slotIndex, water: plot.water, light: plot.light, temperature: plot.temperature, [key]: value })} />)}<button className={s.button} disabled={!plot.ready} onClick={() => onAction({ type: 'HARVEST_CROP', moduleId: plot.moduleId, slotIndex: plot.slotIndex })}>{plot.ready ? 'Harvest crop' : 'Crop growing'}</button></fieldset>{disabledReason && <p>{disabledReason}</p>}</Panel>;
}
export function LivestockPanel({ livestock, onAction, disabledReason, water, temperature }: Controls & { livestock: LivestockState; water?: { text: string; severity: Severity }; temperature?: { text: string; severity: Severity } }) {
  return <Panel title="Livestock" eyebrow={livestock.moduleId}><fieldset className={s.fieldset} disabled={!!disabledReason}><Select<AnimalKind> label="Animal" value={livestock.animal ?? 'chicken'} options={['chicken','pig','cow']} onChange={animal => onAction({ type: 'SET_ANIMAL', moduleId: livestock.moduleId, slotIndex: livestock.slotIndex, animal })} /><Select<LivestockState['feed']> label="Feed level" value={livestock.feed} options={['rationed','normal','high']} onChange={feed => onAction({ type: 'SET_LIVESTOCK_PARAMS', moduleId: livestock.moduleId, slotIndex: livestock.slotIndex, feed })} /></fieldset><p>Water <Status severity={water?.severity}>{water?.text}</Status></p><p>Temperature <Status severity={temperature?.severity}>{temperature?.text}</Status></p>{disabledReason && <p>{disabledReason}</p>}</Panel>;
}
export type AllocationOption = { id: string; label: string; allocation: UtilityAllocation; apCost: number; disabledReason?: string };
export function UtilityPanel({ moduleId, allocation, options, onAction, disabledReason }: Controls & { moduleId: string; allocation: UtilityAllocation; options: readonly AllocationOption[] }) {
  return <Panel title="Utility allocation" eyebrow={moduleId}><dl className={s.stats}>{([['thermal','Thermal'],['backupPower','Backup Power'],['commsBackup','Communication Backup']] as const).map(([key,label]) => <div key={key}><dt>{label}</dt><dd>{(allocation[key] * 100).toFixed(0)}%</dd></div>)}</dl><p className={s.muted}>Small reallocations cost AP and apply immediately.</p>{options.map(option => <div key={option.id}><button className={s.button} disabled={!!disabledReason || !!option.disabledReason} onClick={() => onAction({ type: 'REALLOCATE_UTILITY', moduleId, allocation: option.allocation })}>{option.label} · {option.apCost} AP</button>{option.disabledReason && <p>{option.disabledReason}</p>}</div>)}{!options.length && <p>No reallocation options available.</p>}{disabledReason && <p>{disabledReason}</p>}</Panel>;
}
export function RepairPanel({ targets, onAction, disabledReason }: Controls & { targets: readonly { id: string; label: string; integrity: number; apCost: number; disabledReason?: string }[] }) {
  return <Panel title="Repair station"><p className={s.muted}>Repair keeps the existing layout intact.</p>{!targets.length && <p>No repair targets available.</p>}{targets.map(target => <div key={target.id} className={s.repair}><strong>{target.label}</strong><p>Integrity {(target.integrity * 100).toFixed(0)}%</p><button className={s.button} disabled={!!disabledReason || !!target.disabledReason} onClick={() => onAction({ type: 'REPAIR', targetId: target.id })}>Repair · {target.apCost} AP</button>{target.disabledReason && <p>{target.disabledReason}</p>}</div>)}{disabledReason && <p>{disabledReason}</p>}</Panel>;
}
