import type { MissionReport as ReportData } from '../ai/report';
import type { ScientificSource } from '../ai/schemas';
import { scientificFraming } from '../content/copy';
import { Panel } from './primitives';
import s from './ui.module.css';
export type MissionReportProps = { report: ReportData; nickname: string; scores: { total: number; rules?: number; llm?: number; usedFallback?: boolean }; sources: readonly ScientificSource[] };
export function MissionReport({ report, nickname, scores, sources }: MissionReportProps) {
  const sections = [['Mission Overview', report.overview], ['Production', report.production], ['Stability', report.stability], ['Layout', report.layout], ['Hazards', report.disasterResponse], ['Agriculture', report.agriculture], ['Mission Control', report.missionControl], ['Scientific Context', report.scientificContext], ['Strategy Interpretation', report.strategySuggests]];
  const citations = sources.filter(source => report.sourceIds.includes(source.id) && /^https:\/\//.test(source.url));
  return <div className={s.root}><header className={s.reportHeader}><p className={s.eyebrow}>Mission archive / {nickname}</p><h1>Mission Report <span className={report.result === 'PASS' ? s.normal : s.critical}>{report.result}</span></h1><dl className={s.metrics}><div><dt>Final Score</dt><dd>{scores.total} <small>/ 100</small></dd></div><div><dt>Rule Score</dt><dd>{scores.rules ?? 'Unavailable'} <small>/ 70</small></dd></div><div><dt>LLM Strategy Score</dt><dd>{scores.usedFallback ? 'Unavailable' : scores.llm ?? 'Unavailable'} <small>/ 30</small></dd></div></dl>{scores.usedFallback && <p>Rules-only score normalized by the scoring service; strategy evaluation unavailable.</p>}{report.usedFallback && <p role="status">Template report · AI narrative unavailable</p>}</header><div className={s.reportGrid}>{sections.map(([title,text], i) => <Panel key={title} title={title} eyebrow={`0${i + 1}`}><p>{text}</p></Panel>)}</div><aside className={s.notice}><p>{scientificFraming}</p><p>Your strategy suggests possibilities within this simulation. Comparisons among player runs describe observations, not causal findings.</p></aside><Panel title="Sources">{citations.length ? <ol className={s.sources}>{citations.map(source => <li key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a><p>{source.organization} · {source.shortContext}</p></li>)}</ol> : <p>No verified sources were cited in this report.</p>}</Panel></div>;
}
