"use client";
import { useEffect, useRef, useState, type ReactNode } from 'react';
import './onboarding.css';
/** Approved v10 presentation. Mission creation remains in GameClient. */
export function Onboarding({ form }: { form: ReactNode }) {
 const [screen, setScreen] = useState('welcome');
 const [paused, setPaused] = useState(false);
 const [artStatus, setArtStatus] = useState('loading');
 const host = useRef<HTMLDivElement>(null);
 useEffect(() => {
  const art = new Image();
  art.onload = () => setArtStatus('ready');
  art.onerror = () => setArtStatus('error');
  art.src = '/assets/previews/gameplay-concept-v3.png';
  return () => { art.onload = null; art.onerror = null; };
 }, []);
 useEffect(() => {
  window.scrollTo(0, 0);
  host.current?.querySelector<HTMLElement>(`#${screen === 'introduction' ? 'intro' : screen}-title`)?.focus();
 }, [screen]);
 return <div ref={host} className={`agronaut-onboarding ${paused ? 'motion-off' : ''}`}>
<button className="motion-toggle" id="motion-toggle" aria-pressed={paused} onClick={() => setPaused(!paused)}>{paused ? "Resume animation" : "Pause animation"}</button>
<section id="welcome" hidden={screen !== "welcome"} className="welcome-page" aria-labelledby="welcome-title"><div className="cover"><div className="scene" aria-hidden="true"><svg className="base-art" viewBox="0 160 1120 864" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Pixel-art lunar outpost, displayed without stretching"><image href="/assets/previews/gameplay-concept-v3.png" width="1536" height="1024"/><g aria-hidden="true" className="scene-effects"><ellipse className="grow-light" cx="581" cy="477" rx="86" ry="32" fill="#d9f6a6"/><circle className="beacon" cx="102" cy="420" r="4" fill="#ffd18a"/><circle className="radio radio-one" cx="99" cy="420" r="13"/><circle className="radio radio-two" cx="99" cy="420" r="13"/><path className="flow-track" d="M386 597 L465 551"/><path className="flow-track flow-two" d="M765 547 L844 575"/><circle className="window-light" cx="729" cy="556" r="5" fill="#ffd58b"/></g></svg></div><div className="cover-copy"><p className="brand">◈ agronaut</p><p className="eyebrow">A LITTLE LIFE. A DISTANT WORLD.</p><h1 id="welcome-title" tabIndex={-1}>Make room<br />for life.</h1><p>Build a lunar farm where every harvest depends on the systems keeping it alive.</p><button id="play" onClick={() => setScreen("introduction")}>Play</button><small>Design · Farm · Survive · Learn</small></div><a className="scroll-cue" href="#project-intro">SCROLL TO EXPLORE THE PROJECT ↓</a></div>
<div id="project-intro" className="project-intro"><div className="project-intro-inner"><p className="eyebrow">ABOUT THE PROJECT</p><p className="placeholder-label">PLACEHOLDER COPY · FINAL STORY COMING SOON</p><h2>Growing food is only the beginning.</h2><p className="lead">A short introduction to agronaut will live here: why we built it, what players can explore, and how lunar agriculture connects food production with life-support engineering.</p><div className="project-grid"><article><h3>The idea</h3><p>Placeholder for the project’s motivation and the challenge of designing a farm far from Earth.</p></article><article><h3>The experience</h3><p>Placeholder for the player journey: build an outpost, manage resources, respond to hazards, and reflect on each mission.</p></article><article><h3>The science</h3><p>Placeholder for research context, verified sources, and the distinction between educational simulation and real lunar engineering.</p></article></div><p className="footer">Reserved space for project background, team details, and scientific references.</p><a href="#welcome-title" >Back to Play ↑</a></div></div></section>
<section id="introduction" className="intro" hidden={screen !== "introduction"} aria-labelledby="intro-title"><article><p className="eyebrow">MISSION BRIEFING / LUNAR SOUTH POLE</p><h2 id="intro-title" tabIndex={-1}>A farm is only as strong<br />as its life support.</h2><p>Design your outpost, connect its utilities, and guide it through the lunar environment—one turn at a time.</p><figure className="brief-art" aria-label="Outpost artwork"><svg className="base-art" viewBox="0 160 1120 864" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Pixel-art lunar outpost, displayed without stretching"><image href="/assets/previews/gameplay-concept-v3.png" width="1536" height="1024"/><g aria-hidden="true" className="scene-effects"><ellipse className="grow-light" cx="581" cy="477" rx="86" ry="32" fill="#d9f6a6"/><circle className="beacon" cx="102" cy="420" r="4" fill="#ffd18a"/><circle className="radio radio-one" cx="99" cy="420" r="13"/><circle className="radio radio-two" cx="99" cy="420" r="13"/><path className="flow-track" d="M386 597 L465 551"/><path className="flow-track flow-two" d="M765 547 L844 575"/><circle className="window-light" cx="729" cy="556" r="5" fill="#ffd58b"/></g></svg></figure><div className="steps"><div><span className="number">01</span><b>Design</b><p>Place modules and connect them with utility corridors.</p></div><div><span className="number">02</span><b>Farm</b><p>Care for crops and livestock. Balance water, light and feed.</p></div><div><span className="number">03</span><b>Survive</b><p>Manage scarce resources and respond to hazards.</p></div><div><span className="number">04</span><b>Learn</b><p>Review your mission and explore the trade-offs behind your choices.</p></div></div><p>Once a mission begins, the base layout is locked. Your decisions keep it growing.</p><div className="load" role="status"><span className="dot"></span><span id="load-status">{artStatus === "loading" ? "Loading mission artwork…" : artStatus === "ready" ? "Mission setup ready. Continue when you have finished the briefing." : "Artwork unavailable. You can still continue to mission setup."}</span></div><div className="actions"><button id="continue" disabled={artStatus === "loading"} onClick={() => setScreen("setup")}>Continue</button><button className="quiet" onClick={() => setScreen("welcome")}>Back</button></div><p className="footer">An educational simulation. Lunar livestock is speculative; this game does not predict real-world performance.</p></article></section>
<section id="setup" className="setup" hidden={screen !== "setup"} aria-labelledby="setup-title"><nav className="nav"><strong>◈ agronaut</strong><button className="quiet" onClick={() => setScreen("welcome")}>Back to title</button></nav><div className="setup-grid"><figure className="art-window" aria-label="Illustrative completed lunar outpost in the approved pixel-art style"><div className="scene"><svg className="base-art" viewBox="0 160 1120 864" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Pixel-art lunar outpost, displayed without stretching"><image href="/assets/previews/gameplay-concept-v3.png" width="1536" height="1024"/><g aria-hidden="true" className="scene-effects"><ellipse className="grow-light" cx="581" cy="477" rx="86" ry="32" fill="#d9f6a6"/><circle className="beacon" cx="102" cy="420" r="4" fill="#ffd18a"/><circle className="radio radio-one" cx="99" cy="420" r="13"/><circle className="radio radio-two" cx="99" cy="420" r="13"/><path className="flow-track" d="M386 597 L465 551"/><path className="flow-track flow-two" d="M765 547 L844 575"/><circle className="window-light" cx="729" cy="556" r="5" fill="#ffd58b"/></g></svg></div><figcaption className="art-caption">SOUTH POLE OUTPOST · ILLUSTRATIVE BASE</figcaption></figure><div className="setup-copy"><p className="eyebrow">LUNAR SOUTH POLE / MISSION SIMULATOR</p><h2 id="setup-title" tabIndex={-1}>Build food systems<br /><em>where survival comes first.</em></h2><p>Design an outpost, connect utilities, grow food, and survive the lunar environment.</p>{form}<p className="footer">Illustrative outpost · Your mission begins with an empty map.</p></div></div></section>
</div>;
}
